name: "tutorial"
config-version: 2
version: "1.0.0"

profile: "tutorial"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
    tutorial:
        materialized: table
        # Applies to all files under models/staging/
        staging:
            materialized: view
