version: 2

models:
  - name: stg_customer
    description: Staging view for customer data.
    columns:
      - name: customer_unique_id
        tests:
          - not_null

  - name: stg_orders
    description: Staging view of orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_order_id
        tests:
          - unique
          - not_null

  - name: stg_state
    description: Staging view of states
    columns:
      - name: st
        tests:
          - accepted_values:
              values:
                [
                  "AC",
                  "AL",
                  "AP",
                  "AM",
                  "BA",
                  "CE",
                  "DF",
                  "ES",
                  "GO",
                  "MA",
                  "MT",
                  "MS",
                  "MG",
                  "PA",
                  "PB",
                  "PR",
                  "PE",
                  "PI",
                  "RJ",
                  "RN",
                  "RS",
                  "RO",
                  "RR",
                  "SC",
                  "SP",
                  "SE",
                  "TO",
                ]
